package servidorDeNotificaciones.sop_corba;


/**
* servidorDeNotificaciones/sop_corba/GestionNotificacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones2.idl
* lunes 16 de marzo de 2020 08:32:54 PM COT
*/

public interface GestionNotificacionesOperations 
{
  void notificarRegistro (servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO objNotificacion);
  void notificarAlerta (servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO objNotificacion, servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeAlertaDTO objAlerta);
} // interface GestionNotificacionesOperations
