package servidorDeNotificaciones.sop_corba;


/**
* servidorDeNotificaciones/sop_corba/GestionNotificaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones2.idl
* lunes 16 de marzo de 2020 08:32:54 PM COT
*/

public interface GestionNotificaciones extends GestionNotificacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionNotificaciones
