package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/GestionAlertasInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gestionusuarios3.idl
* sábado 14 de marzo de 2020 06:33:23 PM COT
*/

public interface GestionAlertasInt extends GestionAlertasIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionAlertasInt
