package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/GestionAlertasIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gestionusuarios4.idl
* miércoles 18 de marzo de 2020 07:11:46 PM COT
*/

public interface GestionAlertasIntOperations 
{
  boolean registrarPaciente (servidorDeAlertas.sop_corba.PacienteDTO pacientedto);
  boolean buscarPaciente (int numeroHabitacion, servidorDeAlertas.sop_corba.PacienteDTOHolder objPacienteResultado);
  void modificarPaciente (int numeroHabitacion);
  boolean enviarIndicadores (int numHabitacion, int frecuenciaCardiaca);
} // interface GestionAlertasIntOperations
