package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/GestionAlertasIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gestionusuarios4.idl
* martes 17 de marzo de 2020 05:11:28 PM COT
*/

public interface GestionAlertasIntOperations 
{
  boolean registrarPaciente (servidorDeAlertas.sop_corba.PacienteDTO pacientedto);
  servidorDeAlertas.sop_corba.PacienteDTO buscarPaciente (int numeroHabitacion);
  void modificarPaciente (int numeroHabitacion);
  boolean enviarIndicadores (int numHabitacion, int frecuenciaCardiaca);
} // interface GestionAlertasIntOperations
