package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/PacienteCllbckIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gestionusuarios3.idl
* sábado 14 de marzo de 2020 06:33:23 PM COT
*/

public interface PacienteCllbckIntOperations 
{
  void notificar (int numeroHabitacion, int frecCardiaca);
} // interface PacienteCllbckIntOperations
