package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/PacienteCllbckIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gestionusuarios4.idl
* martes 17 de marzo de 2020 05:11:28 PM COT
*/

public interface PacienteCllbckIntOperations 
{
  void notificar (int numeroHabitacion, int frecCardiaca);
} // interface PacienteCllbckIntOperations
