package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/PacienteCllbckIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gestionusuarios4.idl
* miércoles 18 de marzo de 2020 07:11:46 PM COT
*/

public interface PacienteCllbckIntOperations 
{
  void notificar (int numeroHabitacion, int frecCardiaca);
} // interface PacienteCllbckIntOperations
