package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/PacienteDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gestionusuarios4.idl
* miércoles 18 de marzo de 2020 07:11:46 PM COT
*/

abstract public class PacienteDTOHelper
{
  private static String  _id = "IDL:sop_corba/PacienteDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, servidorDeAlertas.sop_corba.PacienteDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static servidorDeAlertas.sop_corba.PacienteDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "nombre",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "apellido",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "numeroHabitacion",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[3] = new org.omg.CORBA.StructMember (
            "edad",
            _tcOf_members0,
            null);
          _tcOf_members0 = servidorDeAlertas.sop_corba.PacienteCllbckIntHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "pacbck",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (servidorDeAlertas.sop_corba.PacienteDTOHelper.id (), "PacienteDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static servidorDeAlertas.sop_corba.PacienteDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    servidorDeAlertas.sop_corba.PacienteDTO value = new servidorDeAlertas.sop_corba.PacienteDTO ();
    value.nombre = istream.read_string ();
    value.apellido = istream.read_string ();
    value.numeroHabitacion = istream.read_long ();
    value.edad = istream.read_float ();
    value.pacbck = servidorDeAlertas.sop_corba.PacienteCllbckIntHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, servidorDeAlertas.sop_corba.PacienteDTO value)
  {
    ostream.write_string (value.nombre);
    ostream.write_string (value.apellido);
    ostream.write_long (value.numeroHabitacion);
    ostream.write_float (value.edad);
    servidorDeAlertas.sop_corba.PacienteCllbckIntHelper.write (ostream, value.pacbck);
  }

}
