package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/PacienteCllbckIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gestionusuarios4.idl
* miércoles 18 de marzo de 2020 07:11:46 PM COT
*/

public abstract class PacienteCllbckIntPOA extends org.omg.PortableServer.Servant
 implements servidorDeAlertas.sop_corba.PacienteCllbckIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("notificar", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/PacienteCllbckInt/notificar
       {
         int numeroHabitacion = in.read_long ();
         int frecCardiaca = in.read_long ();
         this.notificar (numeroHabitacion, frecCardiaca);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/PacienteCllbckInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PacienteCllbckInt _this() 
  {
    return PacienteCllbckIntHelper.narrow(
    super._this_object());
  }

  public PacienteCllbckInt _this(org.omg.CORBA.ORB orb) 
  {
    return PacienteCllbckIntHelper.narrow(
    super._this_object(orb));
  }


} // class PacienteCllbckIntPOA
