package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/PacienteCllbckInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gestionusuarios3.idl
* sábado 14 de marzo de 2020 06:33:23 PM COT
*/

public interface PacienteCllbckInt extends PacienteCllbckIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PacienteCllbckInt
