package servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage;


/**
* servidorDeNotificaciones/sop_corba/GestionNotificacionesPackage/ClsMensajeAlertaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones2.idl
* lunes 16 de marzo de 2020 08:32:54 PM COT
*/

public final class ClsMensajeAlertaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int frecCardiaca = (int)0;

  public ClsMensajeAlertaDTO ()
  {
  } // ctor

  public ClsMensajeAlertaDTO (int _frecCardiaca)
  {
    frecCardiaca = _frecCardiaca;
  } // ctor

} // class ClsMensajeAlertaDTO
