package servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage;

/**
* servidorDeNotificaciones/sop_corba/GestionNotificacionesPackage/ClsMensajeAlertaDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones2.idl
* lunes 16 de marzo de 2020 08:32:54 PM COT
*/

public final class ClsMensajeAlertaDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeAlertaDTO value = null;

  public ClsMensajeAlertaDTOHolder ()
  {
  }

  public ClsMensajeAlertaDTOHolder (servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeAlertaDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeAlertaDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeAlertaDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeAlertaDTOHelper.type ();
  }

}
