module sop_corba{
 interface PacienteCllbckInt{
	void notificar(in long numeroHabitacion,in long frecCardiaca);
 };
 struct PacienteDTO{
	string nombre;
	string apellido;
	long numeroHabitacion;
	float edad;
	PacienteCllbckInt pacbck;
 };
 interface GestionAlertasInt{
	boolean registrarPaciente(in PacienteDTO pacientedto);
	boolean buscarPaciente(in long numeroHabitacion, out PacienteDTO objPacienteResultado);
	void modificarPaciente(in long numeroHabitacion);
	boolean enviarIndicadores(in long numHabitacion,in long frecuenciaCardiaca);
 };
};