package servidorDeNotificaciones.servidor;

import servidorDeNotificaciones.sop_corba.*;
import servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO;
import servidorDeNotificaciones.sop_corba.GestionNotificacionesPOA;

/**
 * sop_corba/GesAnteproyectosOperations.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from ges_ant.idl martes 9 de julio de 2019
 * 06:45:59 AM COT
 */

public class GesNotificacionesImpl extends GestionNotificacionesPOA {

	public void notificarRegistro(
			servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO objNotificacion) {
		if (objNotificacion.estado == 0) {
			System.out.println("==========NOTIFICACION==========" + "\n" + "FALLO el registro el paciente "
					+ objNotificacion.nombre + " " + objNotificacion.apellido + "\n" + "en la habitacion "
					+ objNotificacion.numeroHabitacion + "\n" + "================================");
		} else {
			System.out.println("==========NOTIFICACION==========" + "\n" + "Se registro el paciente "
					+ objNotificacion.nombre + " " + objNotificacion.apellido + "\n" + "en la habitacion "
					+ objNotificacion.numeroHabitacion + " EXITOSAMENTE\n" + "================================");

		}
	}

	public void notificarAlerta(
			servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO objDatosPaciente,
			servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeAlertaDTO objAlerta) {
		System.out.println("=============ALERTA=============" + "\n" + "El paciente " + objDatosPaciente.nombre + " "
				+ objDatosPaciente.apellido + "\n" + "en la habitacion " + objDatosPaciente.numeroHabitacion + "\n"
				+ "tiene una frecuencia cardiaca irregular de " + objAlerta.frecCardiaca + "\n"
				+ "================================");
	}
}
